#ifndef LUDO_DIMENSIONS_H
#define LUDO_DIMENSIONS_H

#define LEFTY 105.0
#define LEFTX 2.0
#define BORDER 2.0
#define CELLSIZE 35.0

#define OPTIONS_WIDTH 00.0
#define BORDER_WINDOW 4.00
#define RELATIVE_WINDOW_WIDTH .75

#define PIECE_RADIUS 10.00

#define DICE_SIZE 100.0
#define DICE_POSX (LEFTX+7.5*CELLSIZE-DICE_SIZE/2)
#define DICE_POSY 2.00
#define DICE_DOT_RADIUS (DICE_SIZE/10)


#define OPTIONS_POSX 300
#define OPTIONS_POSY 400
#define OPTIONS_LEN  200
#define OPTIONS_WID  40
#define OPTIONS_DIF  100

#define CANCEL_POSX 400
#define CANCEL_POSY 20
#define CANCEL_LEN  75
#define CANCEL_WID  40

#define ROLLBUTTON_POSX 350
#define ROLLBUTTON_POSY 40
#define ROLLBUTTON_LEN  150
#define ROLLBUTTON_WID  40

#endif //LUDO_DIMENSIONS_H
